name: zero_trust_tasks
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nowa_runtime: ^0.1.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  file_picker: ^8.1.6
  intl: ^0.19.0
  pointycastle: ^3.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
